// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using University_Management_System.Data;

#nullable disable

namespace University_Management_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619193900_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("University_Management_System.Models.Course", b =>
                {
                    b.Property<int>("CrsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrsId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowestDegree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CrsId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CrsId = 1,
                            Description = "Core concepts of data organization",
                            HighestDegree = "A",
                            LowestDegree = "D",
                            Name = "Data Structures",
                            Topics = "Arrays,Linked Lists,Trees,Graphs"
                        },
                        new
                        {
                            CrsId = 2,
                            Description = "Differential and integral calculus",
                            HighestDegree = "A",
                            LowestDegree = "D",
                            Name = "Calculus I",
                            Topics = "Limits,Derivatives,Integrals"
                        },
                        new
                        {
                            CrsId = 3,
                            Description = "Logic gates and circuit design",
                            HighestDegree = "A",
                            LowestDegree = "D",
                            Name = "Digital Circuits",
                            Topics = "Boolean Algebra,Gates,Flip-Flops"
                        },
                        new
                        {
                            CrsId = 4,
                            Description = "Design and analysis of algorithms",
                            HighestDegree = "A",
                            LowestDegree = "D",
                            Name = "Algorithms",
                            Topics = "Sorting,Searching,Dynamic Programming"
                        },
                        new
                        {
                            CrsId = 5,
                            Description = "Matrices, vectors and linear systems",
                            HighestDegree = "A",
                            LowestDegree = "D",
                            Name = "Linear Algebra",
                            Topics = "Matrices,Vectors,Eigenvalues"
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.CourseInstructor", b =>
                {
                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "InstructorId");

                    b.HasIndex("InstructorId");

                    b.ToTable("CourseInstructors");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            InstructorId = 1
                        },
                        new
                        {
                            CourseId = 1,
                            InstructorId = 4
                        },
                        new
                        {
                            CourseId = 2,
                            InstructorId = 2
                        },
                        new
                        {
                            CourseId = 3,
                            InstructorId = 3
                        },
                        new
                        {
                            CourseId = 4,
                            InstructorId = 1
                        },
                        new
                        {
                            CourseId = 5,
                            InstructorId = 2
                        },
                        new
                        {
                            CourseId = 5,
                            InstructorId = 5
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.Department", b =>
                {
                    b.Property<int>("DeptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DeptId = 1,
                            Location = "Building A, Floor 2",
                            Name = "Computer Science",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            DeptId = 2,
                            Location = "Building B, Floor 1",
                            Name = "Mathematics",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            DeptId = 3,
                            Location = "Building C, Floor 3",
                            Name = "Electrical Engineering",
                            PhoneNumber = "555-0103"
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.Instructor", b =>
                {
                    b.Property<int>("InsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("InsId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InsId = 1,
                            Address = "12 Oak Street",
                            Age = 45,
                            Degree = "PhD Computer Science",
                            DepartmentId = 1,
                            Email = "s.mitchell@uni.edu",
                            Name = "Dr. Sarah Mitchell",
                            Salary = 85000m
                        },
                        new
                        {
                            InsId = 2,
                            Address = "34 Maple Avenue",
                            Age = 52,
                            Degree = "PhD Mathematics",
                            DepartmentId = 2,
                            Email = "j.okonkwo@uni.edu",
                            Name = "Dr. James Okonkwo",
                            Salary = 92000m
                        },
                        new
                        {
                            InsId = 3,
                            Address = "56 Pine Road",
                            Age = 38,
                            Degree = "PhD Electrical Eng.",
                            DepartmentId = 3,
                            Email = "l.hoffmann@uni.edu",
                            Name = "Dr. Lena Hoffmann",
                            Salary = 78000m
                        },
                        new
                        {
                            InsId = 4,
                            Address = "78 Cedar Lane",
                            Age = 41,
                            Degree = "PhD Computer Science",
                            DepartmentId = 1,
                            Email = "o.farouk@uni.edu",
                            Name = "Dr. Omar Farouk",
                            Salary = 81000m
                        },
                        new
                        {
                            InsId = 5,
                            Address = "90 Birch Blvd",
                            Age = 36,
                            Degree = "MSc Mathematics",
                            DepartmentId = 2,
                            Email = "a.yusuf@uni.edu",
                            Name = "Prof. Amina Yusuf",
                            Salary = 74000m
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Ahmed Hassan"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Sara El-Sayed"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Name = "Mohamed Ali"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            Name = "Nour Khalil"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 2,
                            Name = "Youssef Ibrahim"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Name = "Fatma Mostafa"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 3,
                            Name = "Omar Adel"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 2,
                            Name = "Aya Sherif"
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourse");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 4,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 1,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 2,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 2,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 5,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 3,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 2,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 5,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 1,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 3,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 2,
                            EnrolledOn = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("University_Management_System.Models.CourseInstructor", b =>
                {
                    b.HasOne("University_Management_System.Models.Course", "Course")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Management_System.Models.Instructor", "Instructor")
                        .WithMany("CourseInstructors")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("University_Management_System.Models.Instructor", b =>
                {
                    b.HasOne("University_Management_System.Models.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Management_System.Models.Student", b =>
                {
                    b.HasOne("University_Management_System.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("University_Management_System.Models.StudentCourse", b =>
                {
                    b.HasOne("University_Management_System.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("University_Management_System.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("University_Management_System.Models.Course", b =>
                {
                    b.Navigation("CourseInstructors");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("University_Management_System.Models.Department", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("University_Management_System.Models.Instructor", b =>
                {
                    b.Navigation("CourseInstructors");
                });

            modelBuilder.Entity("University_Management_System.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
